using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CitySelection.WebApi.Models.Domains;
using Microsoft.EntityFrameworkCore;

namespace CitySelection.WebApi.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }
        public DbSet<Country> Countries { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Climate> Climates { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Country>()
                .HasMany(x => x.Cities)
                .WithOne(x => x.Country)
                .HasForeignKey(x => x.CountryId)
                .OnDelete(DeleteBehavior.Cascade);
            modelBuilder.Entity<City>()
            .HasOne(x => x.Climate)
            .WithOne(x => x.City)
            .HasForeignKey<Climate>(x => x.CityId);

            // limitations of data seeding:
            // The primary key value needs to be specified even if it's usually generated by the database. (...)
            // see: https://docs.microsoft.com/en-us/ef/core/modeling/data-seeding

            // for data sources, see Domains classes
            modelBuilder.Entity<Country>().HasData(
                new Country
                {
                    Id = 1,
                    Name = "Poland",
                    GdpPerCapita = 35957,
                    InequalityIndex = 28.5,
                },
                new Country
                {
                    Id = 2,
                    Name = "Germany",
                    GdpPerCapita = 56956,
                    InequalityIndex = 29.7,
                },
                new Country
                {
                    Id = 3,
                    Name = "Netherlands",
                    GdpPerCapita = 60461,
                    InequalityIndex = 26.8,
                },
                new Country
                {
                    Id = 4,
                    Name = "Ireland",
                    GdpPerCapita = 99239,
                    InequalityIndex = 28.9,
                },
                new Country
                {
                    Id = 5,
                    Name = "Denmark",
                    GdpPerCapita = 61478,
                    InequalityIndex = 27.5,
                },
                new Country
                {
                    Id = 6,
                    Name = "France",
                    GdpPerCapita = 49492,
                    InequalityIndex = 28.5,
                },
                new Country
                {
                    Id = 7,
                    Name = "Italy",
                    GdpPerCapita = 43376,
                    InequalityIndex = 33.4,
                },
                new Country
                {
                    Id = 8,
                    Name = "Romania",
                    GdpPerCapita = 32950,
                    InequalityIndex = 34.8,
                }
                );
            modelBuilder.Entity<Climate>().HasData(
                new Climate
                {
                    Id = 1,
                    CityId = 1,
                    RainyDays = 163,
                    MonthlySunshineHours = 1589,
                    Temperature24hAvgHigh = 24.4,
                    Temperature24hAvgLow = -4.2,
                },
                new Climate
                {
                    Id = 2,
                    CityId = 2,
                    RainyDays = 132,
                    MonthlySunshineHours = 1777,
                    Temperature24hAvgHigh = 24.4,
                    Temperature24hAvgLow = -2.5,
                },
                new Climate
                {
                    Id = 3,
                    CityId = 3,
                    RainyDays = 132,
                    MonthlySunshineHours = 1662,
                    Temperature24hAvgHigh = 22.1,
                    Temperature24hAvgLow = 0.8,
                },
                new Climate
                {
                    Id = 4,
                    CityId = 4,
                    RainyDays = 129,
                    MonthlySunshineHours = 1452,
                    Temperature24hAvgHigh = 19.5,
                    Temperature24hAvgLow = 2.3,
                },
                new Climate
                {
                    Id = 5,
                    CityId = 5,
                    RainyDays = 157,
                    MonthlySunshineHours = 1630,
                    Temperature24hAvgHigh = 22.2,
                    Temperature24hAvgLow = -0.8,
                },
                new Climate
                {
                    Id = 6,
                    CityId = 6,
                    RainyDays = 104,
                    MonthlySunshineHours = 2002,
                    Temperature24hAvgHigh = 27.7,
                    Temperature24hAvgLow = 0.3,
                },
                new Climate
                {
                    Id = 7,
                    CityId = 7,
                    RainyDays = 83,
                    MonthlySunshineHours = 1915,
                    Temperature24hAvgHigh = 29.2,
                    Temperature24hAvgLow = -0.9,
                },
                new Climate
                {
                    Id = 8,
                    CityId = 8,
                    RainyDays = 109,
                    MonthlySunshineHours = 2112,
                    Temperature24hAvgHigh = 29.8,
                    Temperature24hAvgLow = -4.8,
                }
                );
            modelBuilder.Entity<City>().HasData(
                new City
                {
                    Id = 1,
                    Name = "Warszawa",
                    EnglishName = "Warsaw",
                    CountryId = 1,
                    Population = 1794,
                    AnnualPM2_5Concentration = 17.0,
                    CostOfLivingIndex = 52,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Warsaw",
                },
                new City
                {
                    Id = 2,
                    Name = "München",
                    EnglishName = "Munich",
                    CountryId = 2,
                    Population = 2606,
                    AnnualPM2_5Concentration = 9.5,
                    CostOfLivingIndex = 79,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Munich",
                },
                new City
                {
                    Id = 3,
                    Name = "Amsterdam",
                    EnglishName = "Amsterdam",
                    CountryId = 3,
                    Population = 1559,
                    AnnualPM2_5Concentration = 11.4,
                    CostOfLivingIndex = 84,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Amsterdam",
                },
                new City
                {
                    Id = 4,
                    Name = "Dublin",
                    EnglishName = "Dublin",
                    CountryId = 4,
                    Population = 1173,
                    AnnualPM2_5Concentration = 8.1,
                    CostOfLivingIndex = 83,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Dublin",
                },
                new City
                {
                    Id = 5,
                    Name = "København",
                    EnglishName = "Copenhagen",
                    CountryId = 5,
                    Population = 1337,
                    AnnualPM2_5Concentration = 10.2,
                    CostOfLivingIndex = 94,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Copenhagen",
                },
                new City
                {
                    Id = 6,
                    Name = "Lyon",
                    EnglishName = "Lyon",
                    CountryId = 6,
                    Population = 1171,
                    AnnualPM2_5Concentration = 11.3,
                    CostOfLivingIndex = 79,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Lyon",
                },
                new City
                {
                    Id = 7,
                    Name = "Milano",
                    EnglishName = "Milan",
                    CountryId = 7,
                    Population = 3400,
                    AnnualPM2_5Concentration = 20.1,
                    CostOfLivingIndex = 78,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Milan",
                },
                new City
                {
                    Id = 8,
                    Name = "București",
                    EnglishName = "Bucharest",
                    CountryId = 8,
                    Population = 2155,
                    AnnualPM2_5Concentration = 16.4,
                    CostOfLivingIndex = 42,
                    WikipediaUrl = "https://en.wikipedia.org/wiki/Bucharest",
                }
                );
        }

    }
}
